version: '3.4'

services:
  docbook.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: ${DOCKER_REGISTRY-}docbookwebapi
    build:
      context: .
      dockerfile: src/DocBook.WebAPI/Dockerfile
    ports:
    - 5000:8080
    - 5001:8081

  mssql-db:
    container_name: mssql-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Str0ngP@ssw0rd!2023"
      ACCEPT_EULA: "Y"

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80